export type Photo = {
    src: string;
    alt?: string;
};

export type Category = {
    slug: string;
    title: string;
    description?: string;
    date?: string;
    cover: string;
    photos: Photo[];
};

export const categories: Category[] = [
    {
        slug: "psg-finale",
        title: "Paris en finale !",
        description: "Reportage photo de Paris fêtant la qualification en finale du PSG.",
        date: "6 mai 2026",
        cover: "/assets/PSG finale/IMG_7654.JPG",
        photos: [
            { src: "/assets/PSG finale/IMG_7654.JPG" },
            { src: "/assets/PSG finale/IMG_7660.JPG" },
            { src: "/assets/PSG finale/IMG_7693.JPG" },
            { src: "/assets/PSG finale/IMG_7743.JPG" },
            { src: "/assets/PSG finale/IMG_7770.JPG" },
            { src: "/assets/PSG finale/IMG_7774.JPG" },
            { src: "/assets/PSG finale/IMG_7776.JPG" },
            { src: "/assets/PSG finale/IMG_7787.JPG" },
            { src: "/assets/PSG finale/IMG_7791.JPG" },
            { src: "/assets/PSG finale/IMG_7792.JPG" },
            { src: "/assets/PSG finale/IMG_7793.JPG" },
            { src: "/assets/PSG finale/IMG_7801.JPG" },
            { src: "/assets/PSG finale/IMG_7803.JPG" },
            { src: "/assets/PSG finale/IMG_7804.JPG" },
            { src: "/assets/PSG finale/IMG_7806.JPG" },
            { src: "/assets/PSG finale/IMG_7807.JPG" },
            { src: "/assets/PSG finale/IMG_7809.JPG" },
            { src: "/assets/PSG finale/IMG_7810.JPG" },
            { src: "/assets/PSG finale/IMG_7828.JPG" },
            { src: "/assets/PSG finale/IMG_7829.JPG" },
            { src: "/assets/PSG finale/IMG_7831.JPG" },
            { src: "/assets/PSG finale/IMG_7843.JPG" },
            { src: "/assets/PSG finale/IMG_7868.JPG" },
            { src: "/assets/PSG finale/IMG_7872.JPG" },
            { src: "/assets/PSG finale/IMG_7925.JPG" },
            { src: "/assets/PSG finale/IMG_7932.JPG" },
            { src: "/assets/PSG finale/IMG_7939.JPG" },
            { src: "/assets/PSG finale/IMG_7960.JPG" },
            { src: "/assets/PSG finale/IMG_7994.JPG" },
            { src: "/assets/PSG finale/IMG_7999.JPG" },
            { src: "/assets/PSG finale/IMG_8061.JPG" },
            { src: "/assets/PSG finale/IMG_8088.JPG" },
            { src: "/assets/PSG finale/IMG_8097.JPG" },
            { src: "/assets/PSG finale/IMG_8136.JPG" },
            { src: "/assets/PSG finale/IMG_8148.JPG" },
            { src: "/assets/PSG finale/IMG_8174.JPG" },
            { src: "/assets/PSG finale/IMG_8194.JPG" },
            { src: "/assets/PSG finale/IMG_8238.JPG" },
        ],
    },
    {
        slug: "event-lacoste",
        title: "Lacoste × Roland Garros",
        description: "Couverture de l'évènement Lacoste en collaboration avec Roland Garros.",
        date: "23 et 24 mai 2026",
        cover: "/assets/Event Lacoste/IMG_5616.JPG",
        photos: [
            { src: "/assets/Event Lacoste/IMG_5616.JPG" },
            { src: "/assets/Event Lacoste/IMG_5704.JPG" },
            { src: "/assets/Event Lacoste/IMG_5719.JPG" },
            { src: "/assets/Event Lacoste/IMG_5796.JPG" },
            { src: "/assets/Event Lacoste/IMG_5807.JPG" },
            { src: "/assets/Event Lacoste/IMG_5909.JPG" },
            { src: "/assets/Event Lacoste/IMG_5916.JPG" },
            { src: "/assets/Event Lacoste/IMG_6039.JPG" },
            { src: "/assets/Event Lacoste/IMG_6203.JPG" },
            { src: "/assets/Event Lacoste/IMG_6216.JPG" },
            { src: "/assets/Event Lacoste/IMG_6264.JPG" },
            { src: "/assets/Event Lacoste/IMG_6344.JPG" },
            { src: "/assets/Event Lacoste/IMG_6353.JPG" },
            { src: "/assets/Event Lacoste/IMG_6410.JPG" },
            { src: "/assets/Event Lacoste/IMG_6410 2.JPG" },
            { src: "/assets/Event Lacoste/IMG_6517.JPG" },
            { src: "/assets/Event Lacoste/IMG_6522.JPG" },
            { src: "/assets/Event Lacoste/IMG_6575.JPG" },
            { src: "/assets/Event Lacoste/IMG_6761.JPG" },
            { src: "/assets/Event Lacoste/IMG_6779.JPG" },
            { src: "/assets/Event Lacoste/IMG_6786.JPG" },
            { src: "/assets/Event Lacoste/IMG_6810.JPG" },
            { src: "/assets/Event Lacoste/IMG_6814.JPG" },
            { src: "/assets/Event Lacoste/IMG_6869.JPG" },
            { src: "/assets/Event Lacoste/IMG_6888.JPG" },
            { src: "/assets/Event Lacoste/IMG_6892.JPG" },
            { src: "/assets/Event Lacoste/IMG_6916.JPG" },
            { src: "/assets/Event Lacoste/IMG_6921.JPG" },
            { src: "/assets/Event Lacoste/IMG_7041.JPG" },
            { src: "/assets/Event Lacoste/IMG_7064.JPG" },
            { src: "/assets/Event Lacoste/IMG_7071.JPG" },
            { src: "/assets/Event Lacoste/IMG_7075.JPG" },
            { src: "/assets/Event Lacoste/IMG_7089.JPG" },
            { src: "/assets/Event Lacoste/IMG_7091.jpg" },
            { src: "/assets/Event Lacoste/IMG_7093.JPG" },
            { src: "/assets/Event Lacoste/IMG_7095.JPG" },
        ],
    },
    {
        slug: "aya-nakamura",
        title: "Concert Aya Nakamura",
        description: "Shooting aux abords du Stade de France pour le concert d'Aya Nakamura avec quelques fans.",
        date: "29 mai 2026",
        cover: "/assets/Aya Nakamura/IMG_7318.JPG",
        photos: [
            { src: "/assets/Aya Nakamura/IMG_7635.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7318.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7320.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7324.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7345.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7350.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7353.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7472.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7488.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7491.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7495.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7496.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7500.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7503.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7505.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7509.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7523.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7524.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7534.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7566.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7567.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7585.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7591.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7591 2.JPG" },
            { src: "/assets/Aya Nakamura/IMG_7630.JPG" },
        ],
    },
    {
        slug: "psg-1",
        title: "Back to Back du Paris Saint-Germain",
        description: "Reportage photo de Paris fêtant la Ligue des champions face à Arsenal.",
        date: "30 mai 2025",
        cover: "/assets/PSG 1 /IMG_6849.jpg",
        photos: [
            { src: "/assets/PSG 1 /IMG_6849.jpg" },
            { src: "/assets/PSG 1 /IMG_6850.jpg" },
            { src: "/assets/PSG 1 /IMG_6860.jpg" },
            { src: "/assets/PSG 1 /IMG_6894.jpg" },
            { src: "/assets/PSG 1 /IMG_6895.jpg" },
            { src: "/assets/PSG 1 /IMG_6900.jpg" },
            { src: "/assets/PSG 1 /IMG_6904.jpg" },
            { src: "/assets/PSG 1 /IMG_6907.jpg" },
            { src: "/assets/PSG 1 /IMG_6910.jpg" },
            { src: "/assets/PSG 1 /IMG_6970.JPG" },
            { src: "/assets/PSG 1 /IMG_6976.jpg" },
            { src: "/assets/PSG 1 /IMG_6989.jpg" },
            { src: "/assets/PSG 1 /IMG_6998.jpg" },
            { src: "/assets/PSG 1 /IMG_7014.jpg" },
            { src: "/assets/PSG 1 /IMG_7021.jpg" },
            { src: "/assets/PSG 1 /IMG_7025.jpg" },
            { src: "/assets/PSG 1 /IMG_7033.jpg" },
            { src: "/assets/PSG 1 /IMG_7037.jpg" },
            { src: "/assets/PSG 1 /IMG_7039.JPG" },
            { src: "/assets/PSG 1 /IMG_7040.jpg" },
            { src: "/assets/PSG 1 /IMG_7051.jpg" },
            { src: "/assets/PSG 1 /IMG_7052.jpg" },
            { src: "/assets/PSG 1 /IMG_7104.jpg" },
            { src: "/assets/PSG 1 /IMG_7115.JPG" },
            { src: "/assets/PSG 1 /IMG_7119.jpg" },
            { src: "/assets/PSG 1 /IMG_7133.jpg" },
            { src: "/assets/PSG 1 /IMG_7134.jpg" },
            { src: "/assets/PSG 1 /IMG_7152.jpg" },
            { src: "/assets/PSG 1 /IMG_7153.jpg" },
            { src: "/assets/PSG 1 /IMG_7155.jpg" },
            { src: "/assets/PSG 1 /IMG_7174.jpg" },
            { src: "/assets/PSG 1 /IMG_7176.jpg" },
            { src: "/assets/PSG 1 /IMG_7180.jpg" },
            { src: "/assets/PSG 1 /IMG_7190.JPG" },
            { src: "/assets/PSG 1 /IMG_7191.jpg" },
            { src: "/assets/PSG 1 /IMG_7192.jpg" },
            { src: "/assets/PSG 1 /IMG_7197.JPG" },
            { src: "/assets/PSG 1 /IMG_7199.jpg" },
            { src: "/assets/PSG 1 /IMG_7203.jpg" },
            { src: "/assets/PSG 1 /IMG_7207.jpg" },
            { src: "/assets/PSG 1 /IMG_7225.jpg" },
            { src: "/assets/PSG 1 /IMG_7228.jpg" },
            { src: "/assets/PSG 1 /IMG_7252.JPG" },
            { src: "/assets/PSG 1 /IMG_7260.jpg" },
            { src: "/assets/PSG 1 /IMG_7388.jpg" },
            { src: "/assets/PSG 1 /IMG_7389.jpg" },
            { src: "/assets/PSG 1 /IMG_7400.jpg" },
            { src: "/assets/PSG 1 /IMG_7403.jpg" },
            { src: "/assets/PSG 1 /IMG_7414.jpg" },
            { src: "/assets/PSG 1 /IMG_7421.jpg" },
            { src: "/assets/PSG 1 /IMG_7427.jpg" },
            { src: "/assets/PSG 1 /IMG_7436.jpg" },
            { src: "/assets/PSG 1 /IMG_7461.jpg" },
            { src: "/assets/PSG 1 /IMG_7466.jpg" },
            { src: "/assets/PSG 1 /IMG_7470.JPG" },
            { src: "/assets/PSG 1 /IMG_7471.jpg" },
        ],
    },
];

export function getCategoryBySlug(slug: string): Category | undefined {
    return categories.find((c) => c.slug === slug);
}
